package view;
import controller.DocGiaController;
import controller.LoginController;
import controller.NhanVienController;
import model.Session;
import dao.AccountDAO;
import model.Account;
import javax.swing.JOptionPane;
import model.DocGia;
import model.NhanVien;




/**
 *
 * @author Bao Quyen
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setTitle("ĐĂNG NHẬP HỆ THỐNG");
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        ButtonDangKy = new javax.swing.JButton();
        ButtonDangNhap = new javax.swing.JButton();
        ButtonThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonDangKy.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ButtonDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-registration-24.png"))); // NOI18N
        ButtonDangKy.setText("Đăng Ký");
        ButtonDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDangKyActionPerformed(evt);
            }
        });

        ButtonDangNhap.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ButtonDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-login-24.png"))); // NOI18N
        ButtonDangNhap.setText("Đăng Nhập");
        ButtonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDangNhapActionPerformed(evt);
            }
        });

        ButtonThoat.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-exit-24.png"))); // NOI18N
        ButtonThoat.setText("Thoát");
        ButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThoatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Password :");

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setText("Tên Đăng Nhập :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-library-100.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ButtonDangKy)
                        .addGap(41, 41, 41)
                        .addComponent(ButtonDangNhap)
                        .addGap(35, 35, 35)
                        .addComponent(ButtonThoat)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDangKy)
                    .addComponent(ButtonDangNhap)
                    .addComponent(ButtonThoat))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDangNhapActionPerformed
        // TODO add your handling code here:
      String user = txtUsername.getText();
      String pass = new String(txtPassword.getPassword());

if (user.isEmpty() || pass.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Nhập đủ tài khoản và mật khẩu!");
    return;
}

LoginController controller = new LoginController();
Account acc = AccountDAO.login(user, pass);
if (acc != null) {
   Session.currentAccount = acc; 
   int quyen = acc.getQuyen();
    if (quyen == 0) {
        new AdminForm().setVisible(true);
    }
    else if (quyen == 1) {
int maDocGia = acc.getMaDocGia();
//System.out.println("✅ LOGIN OK - MaDocGia = " + maDocGia);
// mã độc giả
DocGiaController dgController = new DocGiaController();
DocGia dg = dgController.layThongTin(maDocGia);

// ✅ SET SESSION
Session.currentUser = dg;
Session.currentNhanVien = null;

// ✅ TRUYỀN MÃ ĐỘC GIẢ
new DocGiaForm(maDocGia).setVisible(true);
   // new DocGiaForm().setVisible(true);
    }
    else if (quyen == 2) { 
  
        NhanVienController nvController = new NhanVienController();
        NhanVien nv = nvController.layThongTin(acc.getMaNV());
        Session.currentNhanVien = nv; 
        Session.currentUser = null;
        new NhanVienForm().setVisible(true);
    }
    this.dispose();
} else {
    JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu!");
}
    }//GEN-LAST:event_ButtonDangNhapActionPerformed

    private void ButtonDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDangKyActionPerformed
        // TODO add your handling code here:
        
        // mở giao diện Đăng Ký
        new RegisterForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButtonDangKyActionPerformed

    private void ButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDangKy;
    private javax.swing.JButton ButtonDangNhap;
    private javax.swing.JButton ButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
